<?
$arTooltips = array(
	"URL_SUBDOMAIN" => GetMessage("URL_SUBDOMAIN_TIP"),
	"PATH_VHOST" => GetMessage("PATH_VHOST_TIP"),
	"MYSQL_PATH" => GetMessage("MYSQL_PATH_TIP"),
	"MYSQL_USER" => GetMessage("MYSQL_USER_TIP"),
	"MYSQL_PASSWORD" => GetMessage("MYSQL_PASSWORD_TIP"),
	"SET_TITLE" => GetMessage("SET_TITLE_TIP"),
	"CONTROLLER_URL" => GetMessage("CONTROLLER_URL_TIP"),
	"MYSQL_DB_PATH" => GetMessage("MYSQL_DB_PATH_TIP"),
	"DIR_PERMISSIONS" => GetMessage("DIR_PERMISSIONS_TIP"),
	"FILE_PERMISSIONS" => GetMessage("FILE_PERMISSIONS_TIP"),
	"PATH_PUBLIC" => GetMessage("PATH_PUBLIC_TIP"),
	"MEMORY_LIMIT" => GetMessage("MEMORY_LIMIT_TIP"),
	"APACHE_ROOT" => GetMessage("APACHE_ROOT_TIP"),
	"NGINX_ROOT" => GetMessage("NGINX_ROOT_TIP"),
	"RELOAD_FILE" => GetMessage("RELOAD_FILE_TIP"),
);
?>