<?
    $aMenuLinks = Array(
        Array(
            "Направление", 
            "/formation-tours/direction/", 
            Array(), 
            Array(), 
            "" 
        ),
        Array(
            "Города", 
            "/formation-tours/city/", 
            Array(), 
            Array(), 
            "" 
        ),
        Array(
            "Гостиницы", 
            "/formation-tours/hotel/", 
            Array(), 
            Array(), 
            "" 
        ),

        Array(
            "Номера", 
            "/formation-tours/room/", 
            Array(), 
            Array(), 
            "" 
        ),
        Array(
            "Автобусы", 
            "/formation-tours/bus/", 
            Array(), 
            Array(), 
            "" 
        ),  

    );
?>